force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/Crew_Member__c.field-meta.xml
<CustomField>
    <fullName>Crew_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crew Member</label>
    <referenceTo>Crew_Member__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <referenceTo>Passenger__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <referenceTo>Passenger__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Crew_Member__c/Crew_Member__c.object-meta.xml
<CustomObject>
    <label>Crew Member</label>
    <nameField>
        <label>Crew Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crew Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Crew_Member__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight Number</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Crew Members</relationshipLabel>
    <relationshipName>Crew_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Crew_Member__c/fields/Passenger_Count__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Count__c</fullName>
    <label>Passenger Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>FL-{0000}</displayFormat>
        <label>Flight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Arrival__c.field-meta.xml
<CustomField>
    <fullName>Arrival__c</fullName>
    <label>Arrival</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Departure__c.field-meta.xml
<CustomField>
    <fullName>Departure__c</fullName>
    <label>Departure</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahmedabad - AMD</fullName>
            </value>
            <value>
                <fullName>Bengaluru - BLR</fullName>
            </value>
            <value>
                <fullName>Bhopal - BHO</fullName>
            </value>
            <value>
                <fullName>Delhi - DEL</fullName>
            </value>
            <value>
                <fullName>Goa - GOI</fullName>
            </value>
            <value>
                <fullName>Hyderabad - HYD</fullName>
            </value>
            <value>
                <fullName>Kolkata - CCU</fullName>
            </value>
            <value>
                <fullName>Mumbai - BOM</fullName>
            </value>
            <value>
                <fullName>Nagpur - NAG</fullName>
            </value>
            <value>
                <fullName>Pune - PNQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahmedabad - AMD</fullName>
            </value>
            <value>
                <fullName>Bengaluru - BLR</fullName>
            </value>
            <value>
                <fullName>Bhopal - BHO</fullName>
            </value>
            <value>
                <fullName>Delhi - DEL</fullName>
            </value>
            <value>
                <fullName>Goa - GOI</fullName>
            </value>
            <value>
                <fullName>Hyderabad - HYD</fullName>
            </value>
            <value>
                <fullName>Kolkata - CCU</fullName>
            </value>
            <value>
                <fullName>Mumbai - BOM</fullName>
            </value>
            <value>
                <fullName>Nagpur - NAG</fullName>
            </value>
            <value>
                <fullName>Pune - PNQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DashboardControllerTest.cls
@isTest
public class DashboardControllerTest {
    @isTest
    static void testDashboardController() {

        Flight__c testFlight = new Flight__c(Origin__c='Delhi - DEL', Destination__c='Hyderabad - HYD', Departure__c=DateTime.valueOf('2024-06-06 06:30:00'), Arrival__c=DateTime.valueOf('2024-06-06 08:00:00'));

        insert testFlight;

        Crew_Member__c testCrewMember = new Crew_Member__c(Name='TestCrewMember', Flight_Number__c=testFlight.Id);
        insert testCrewMember;

        Passenger__c testPassenger = new Passenger__c(Name='TestPassenger');
        insert testPassenger;

        Booking__c testBooking = new Booking__c(Flight__c=testFlight.Id, Passenger__c=testPassenger.Id);
        insert testBooking;

        Assignment__c testAssignment = new Assignment__c(Crew_Member__c=testCrewMember.Id, Passenger__c=testPassenger.Id);
        insert testAssignment;

        Test.startTest();
        Flight__c fc = [Select Name from Flight__c where Id = :testFlight.Id];
        List<Passenger__c> passengers1 = DashboardController.getPassengerData(fc.Name, '');
        System.assertEquals(1, passengers1.size());

        List<Passenger__c> passengers2 = DashboardController.getPassengerData('', 'TestCrewMember');
        System.assertEquals(1, passengers2.size());

        List<Passenger__c> passengers3 = DashboardController.getPassengerData('', '');
        System.assertEquals(1, passengers3.size());

        // Test getFlightData method
        List<Flight__c> flights1 = DashboardController.getFlightData(fc.Name, '');
        System.assertEquals(1, flights1.size());

        List<Flight__c> flights2 = DashboardController.getFlightData('', 'TestCrewMember');
        System.assertEquals(1, flights2.size());

        List<Flight__c> flights3 = DashboardController.getFlightData('', '');
        System.assertEquals(1, flights3.size());
        // Test getCrewMemberData method
        List<Crew_Member__c> crewMembers1 = DashboardController.getCrewMemberData(fc.Name, '');
        System.assertEquals(1, crewMembers1.size());

        List<Crew_Member__c> crewMembers2 = DashboardController.getCrewMemberData('', 'TestCrewMember');
        System.assertEquals(1, crewMembers2.size());

        List<Crew_Member__c> crewMembers3 = DashboardController.getCrewMemberData('', '');
        System.assertEquals(1, crewMembers3.size());
        // Test getFlightOptions method
        List<Flight__c> flightOptions = DashboardController.getFlightOptions();
        System.assertEquals(1, flightOptions.size());

        // Test getCrewMemberOptions method
        List<Crew_Member__c> crewMemberOptions = DashboardController.getCrewMemberOptions();
        System.assertEquals(1, crewMemberOptions.size());

        //Test Bookingtrigger
        Flight__c f = [Select Passenger_Count__c from Flight__c where Id=:testFlight.Id];
        System.assertEquals(1, f.Passenger_Count__c);

        
        //Test Assignmenttrigger
        Crew_Member__c c = [Select Passenger_Count__c from Crew_Member__c where Id=:testCrewMember.Id];
        System.assertEquals(1, c.Passenger_Count__c);

        Test.stopTest();

    }
}