force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/Crew_Member__c.field-meta.xml
<CustomField>
    <fullName>Crew_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crew Member</label>
    <referenceTo>Crew_Member__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <referenceTo>Passenger__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <referenceTo>Passenger__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Crew_Member__c/Crew_Member__c.object-meta.xml
<CustomObject>
    <label>Crew Member</label>
    <nameField>
        <label>Crew Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crew Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Crew_Member__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight Number</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Crew Members</relationshipLabel>
    <relationshipName>Crew_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Crew_Member__c/fields/Passenger_Count__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Count__c</fullName>
    <label>Passenger Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>FL-{0000}</displayFormat>
        <label>Flight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Arrival__c.field-meta.xml
<CustomField>
    <fullName>Arrival__c</fullName>
    <label>Arrival</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Departure__c.field-meta.xml
<CustomField>
    <fullName>Departure__c</fullName>
    <label>Departure</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahmedabad - AMD</fullName>
            </value>
            <value>
                <fullName>Bengaluru - BLR</fullName>
            </value>
            <value>
                <fullName>Bhopal - BHO</fullName>
            </value>
            <value>
                <fullName>Delhi - DEL</fullName>
            </value>
            <value>
                <fullName>Goa - GOI</fullName>
            </value>
            <value>
                <fullName>Hyderabad - HYD</fullName>
            </value>
            <value>
                <fullName>Kolkata - CCU</fullName>
            </value>
            <value>
                <fullName>Mumbai - BOM</fullName>
            </value>
            <value>
                <fullName>Nagpur - NAG</fullName>
            </value>
            <value>
                <fullName>Pune - PNQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahmedabad - AMD</fullName>
            </value>
            <value>
                <fullName>Bengaluru - BLR</fullName>
            </value>
            <value>
                <fullName>Bhopal - BHO</fullName>
            </value>
            <value>
                <fullName>Delhi - DEL</fullName>
            </value>
            <value>
                <fullName>Goa - GOI</fullName>
            </value>
            <value>
                <fullName>Hyderabad - HYD</fullName>
            </value>
            <value>
                <fullName>Kolkata - CCU</fullName>
            </value>
            <value>
                <fullName>Mumbai - BOM</fullName>
            </value>
            <value>
                <fullName>Nagpur - NAG</fullName>
            </value>
            <value>
                <fullName>Pune - PNQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Passenger__c/fields/Passport__c.field-meta.xml
<CustomField>
    <fullName>Passport__c</fullName>
    <label>Passport</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DashboardController.cls
public with sharing class DashboardController {

    
    @AuraEnabled(cacheable=true)
    public static List<Passenger__c> getPassengerData(String flightNumber, String crewMemberName){

        List<Passenger__c> pass = new List<Passenger__c>();
        List<Assignment__c> assignment = new List<Assignment__c>();
        List<Booking__c> booking = new List<Booking__c>();
        if (Schema.sObjectType.Passenger__c.isAccessible() ){
            if(flightNumber != ''){
                booking = [SELECT Passenger__c from Booking__c where Flight__r.Name =:flightNumber];
                Set<Id> bookingSet = new Set<Id>();
                for(Booking__c book : booking){
                    bookingSet.add(book.Passenger__c);
                }
                pass = [SELECT Name, Country__c, Address__c, Passport__c from Passenger__c where Id in :bookingSet order by Name asc];
            }
            else if(crewMemberName != ''){
                assignment = [SELECT Passenger__c from Assignment__c where Crew_Member__r.Name=:crewMemberName];

                Set<Id> assignmentSet = new Set<Id>();
                for(Assignment__c assign : assignment){
                    assignmentSet.add(assign.Passenger__c);
                }
                pass = [SELECT Name, Country__c, Address__c, Passport__c from Passenger__c where Id in :assignmentSet order by Name asc];
            }
            else{
                pass = [SELECT Name, Country__c, Address__c, Passport__c from Passenger__c order by Name asc];
            }
        }
        return pass;
    }

    @AuraEnabled(cacheable=true)
    public static List<Flight__c> getFlightData(String flightNumber, String crewMemberName){

        List<Flight__c> flight = new List<Flight__c>();
        if (Schema.sObjectType.Flight__c.isAccessible() && Schema.sObjectType.Crew_Member__c.isAccessible()){
            if(flightNumber != ''){
                flight = [SELECT Name,Origin__c,Departure__c, Destination__c, Arrival__c, Passenger_Count__c from Flight__c where Name=:flightNumber order by Name asc];
            }
            else if(crewMemberName != ''){
                flight = [SELECT Name,Origin__c,Departure__c, Destination__c, Arrival__c, Passenger_Count__c from Flight__c where Id in (SELECT Flight_Number__c from Crew_Member__c where Name=:crewMemberName) order by Name asc];
            }
            else{
                flight = [SELECT Name,Origin__c,Departure__c, Destination__c, Arrival__c, Passenger_Count__c from Flight__c order by Name asc];
            }
        }
        return flight;
    }

    @AuraEnabled(cacheable=true)
    public static List<Crew_Member__c> getCrewMemberData(String flightNumber, String crewMemberName){

        List<Crew_Member__c> crewMember = new List<Crew_Member__c>();
        if (Schema.sObjectType.Crew_Member__c.isAccessible() ){
            if(flightNumber != '')
                crewMember = [SELECT Name, Flight_Number__r.Name, Passenger_Count__c from Crew_Member__c where Flight_Number__r.Name=:flightNumber order by Name asc];
            else if(crewMemberName != '')
                crewMember = [SELECT Name, Flight_Number__r.Name, Passenger_Count__c from Crew_Member__c where Name=:crewMemberName order by Name asc];
            else
                crewMember = [SELECT Name, Flight_Number__r.Name, Passenger_Count__c from Crew_Member__c order by Name asc];
        }
        return crewMember;
    }

    @AuraEnabled(cacheable=true)
    public static List<Flight__c> getFlightOptions(){

        List<Flight__c> flight = new List<Flight__c>();
        if (Schema.sObjectType.Flight__c.isAccessible()){
            flight = [Select name from Flight__c order by name asc];
        }
        return flight;
    }

    @AuraEnabled(cacheable=true)
    public static List<Crew_Member__c> getCrewMemberOptions(){

        List<Crew_Member__c> crewMember = new List<Crew_Member__c>();
        if (Schema.sObjectType.Crew_Member__c.isAccessible()){
            crewMember = [Select name from Crew_Member__c order by name asc];
        }
        return crewMember;
    }
}